---
title: "Homework 5"
author: "RuiJun Chen"
date: "11/11/2019"
output: github_document
---

```{r setup, include = FALSE}
library(tidyverse)
library(rvest)
knitr::opts_chunk$set(
	echo = TRUE,
	warning = FALSE,
	fig.width = 8, 
  fig.height = 6,
  out.width = "90%"
)
options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)
scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
theme_set(theme_minimal() + theme(legend.position = "bottom"))
```

## Problem 1
```{r}
set.seed(10)

iris_with_missing = iris %>% 
  map_df(~replace(.x, sample(1:150, 20), NA)) %>%
  mutate(Species = as.character(Species))

iris_with_missing = iris_with_missing %>% janitor::clean_names()

fill_missing = function(x) {
  if (is.numeric(x)) {
    x = x %>% replace_na(mean(x, na.rm = TRUE))
  } else if (is.character(x)) {
    x = x %>% replace_na("virginica")
  } else {
    stop("x is neither numeric nor a character")
  }
}

iris_filled =
  map(iris_with_missing, fill_missing) %>% 
  bind_rows()

iris_filled
```

## Problem 2

```{r}
study_pts = 
  list.files(path = "./data") %>% 
  enframe(name = NULL, value = "path") %>% 
  mutate(        #read in every CSV using map after appending ./data/ to get correct path
    path = str_c("./data/",path),
    data = map(path, read_csv, col_types = "dddddddd")
  ) %>% 
  unnest(data) %>%    #un-nest all weeks of data
  mutate(     #extract patient ID and experiment arm
    patient_id = substr(path, 12, 13),
    arm = substr(path, 8, 10)
  ) %>% 
  select(-path) %>% 
  pivot_longer(     #makes data more tidy for analysis
    week_1:week_8,
    names_to = "week",
    values_to = "outcome"
  ) %>% 
  mutate(
    week = as.numeric(substr(week, 6,6))
  )

study_pts
```

```{r}
study_pts %>% 
  ggplot(aes(x = week, y = outcome, color = patient_id)) +
  geom_line() +
  facet_grid(~arm)
```

For whatever the outcome is, the patients in the experimental arm seem to have increasing values over time, a positive correlation with the experimental exposure over time. The control arm appears to have slightly lower values at baseline and have no clear correlation (or slightly negative correlation) over time.

## Problem 3
